from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSlot


class Ui_MainWindow(QObject):
    """Contains main information about GUI. Variables are:
    browse_file_button - browse file button
    provided_hash_line - hash code given by developer, i.e. the original, correct hash code
    input_file_line - where the file is dropped or the browse button provides a path to the file
    computed_hash_line - shell command fills this, the hash code of the actual file"""
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 557)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.md5_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        self.md5_radio_button.setGeometry(QtCore.QRect(290, 90, 100, 20))
        self.md5_radio_button.setObjectName("md5_radio_button")
        self.sha1_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        self.sha1_radio_button.setGeometry(QtCore.QRect(420, 90, 100, 20))
        self.sha1_radio_button.setObjectName("sha1_radio_button")
        self.sha256_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        self.sha256_radio_button.setGeometry(QtCore.QRect(540, 90, 100, 20))
        self.sha256_radio_button.setObjectName("sha256_radio_button")
        self.browse_file_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_file_button.setGeometry(QtCore.QRect(130, 80, 120, 34))
        self.browse_file_button.setObjectName("browse_file_button")
        self.provided_hash_line = QtWidgets.QLineEdit(self.centralwidget)
        self.provided_hash_line.setGeometry(QtCore.QRect(280, 160, 471, 21))
        self.provided_hash_line.setObjectName("provided_hash_line")
        self.file_hash_label = QtWidgets.QLabel(self.centralwidget)
        self.file_hash_label.setGeometry(QtCore.QRect(40, 60, 231, 16))
        self.file_hash_label.setObjectName("file_hash_label")
        self.comparison_hash_label = QtWidgets.QLabel(self.centralwidget)
        self.comparison_hash_label.setGeometry(QtCore.QRect(40, 160, 131, 21))
        self.comparison_hash_label.setObjectName("comparison_hash_label")
        self.compare_hashes_button = QtWidgets.QPushButton(self.centralwidget)
        self.compare_hashes_button.setGeometry(QtCore.QRect(610, 450, 141, 32))
        self.compare_hashes_button.setObjectName("compare_hashes_button")
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(450, 450, 113, 32))
        self.reset_button.setObjectName("reset_button")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(40, 450, 113, 32))
        self.exit_button.setObjectName("exit_button")
        self.computed_hash_line = QtWidgets.QLineEdit(self.centralwidget)
        self.computed_hash_line.setGeometry(QtCore.QRect(280, 240, 471, 21))
        self.computed_hash_line.setObjectName("computed_hash_line")
        self.results_line = QtWidgets.QLineEdit(self.centralwidget)
        self.results_line.setGeometry(QtCore.QRect(300, 370, 325, 21))
        self.results_line.setObjectName("results_line")
        self.results_label = QtWidgets.QLabel(self.centralwidget)
        self.results_label.setGeometry(QtCore.QRect(230, 370, 60, 16))
        self.results_label.setObjectName("results_label")
        self.computed_hash_label = QtWidgets.QLabel(self.centralwidget)
        self.computed_hash_label.setGeometry(QtCore.QRect(40, 240, 225, 16))
        self.computed_hash_label.setObjectName("computed_hash_label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(27, 310, 731, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 0, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 22))
        self.menubar.setObjectName("menubar")
        self.menuHash = QtWidgets.QMenu(self.menubar)
        self.menuHash.setObjectName("menuHash")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHash.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.md5_radio_button.setText(_translate("MainWindow", "MD5"))
        self.sha1_radio_button.setText(_translate("MainWindow", "SHA-1"))
        self.sha256_radio_button.setText(_translate("MainWindow", "SHA-256"))
        self.file_hash_label.setText(_translate("MainWindow", "Drag and Drop File or Browse File Path"))
        self.comparison_hash_label.setText(_translate("MainWindow", "Paste Provided Hash"))
        self.compare_hashes_button.setText(_translate("MainWindow", "Compare Hashes"))
        self.browse_file_button.setText(_translate("MainWindow", "Browse Files"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))
        self.results_label.setText(_translate("MainWindow", "Results:"))
        self.computed_hash_label.setText(_translate("MainWindow", "Computed Hash of File Provided"))
        self.label.setText(_translate("MainWindow", "Security Hash Comparison"))
        self.menuHash.setTitle(_translate("MainWindow", "Hash"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
